[package]
name          = "waltz-persistence-postgres"
description   = "PostgreSQL event and snapshot stores for waltz persistence"
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
homepage      = { workspace = true }
repository    = { workspace = true }
documentation = { workspace = true }
publish       = { workspace = true }

[dependencies]
sqlx      = { workspace = true, features = [ "runtime-tokio", "tls-rustls-ring", "postgres", "migrate", "macros" ] }
thiserror = { workspace = true }
waltz     = { workspace = true, features = [ "persistence" ] }

[dev-dependencies]
anyhow                 = { workspace = true }
composed               = { workspace = true }
serde                  = { workspace = true, features = [ "derive" ] }
testcontainers-modules = { workspace = true, features = [ "postgres" ] }
tokio                  = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
tracing-subscriber     = { workspace = true, features = [ "env-filter", "fmt", "json" ] }
waltz                  = { workspace = true, features = [ "persistence-tests" ] }
